"""enforce unique supplier proposal per event

Revision ID: 77be063f5e71
Revises: 0d5b70e1dddb
Create Date: 2026-10-06 01:02:01.895190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77be063f5e71'
down_revision: Union[str, Sequence[str], None] = '0d5b70e1dddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_proposal_supplier_event', 'proposals', ['supplier_id', 'procurement_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_proposal_supplier_event', 'proposals', type_='unique')
    # ### end Alembic commands ###
