"""add document storage key

Revision ID: 786057834eda
Revises: 947d530c43ef
Create Date: 2026-10-06 16:07:35.736565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786057834eda'
down_revision: Union[str, Sequence[str], None] = '947d530c43ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('storage_key', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'storage_key')
    # ### end Alembic commands ###
